
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Copy, FileCode } from "lucide-react";
import { toast } from "sonner";

interface CodeViewerProps {
  code: string;
}

export const CodeViewer = ({ code }: CodeViewerProps) => {
  const handleCopyCode = () => {
    navigator.clipboard.writeText(code);
    toast.success("Code copied to clipboard!");
  };

  const formatArduinoCode = (rawCode: string) => {
    if (!rawCode.trim()) {
      return `// Arduino Sketch
// Add blocks to generate code

void setup() {
  // Initialization code goes here
}

void loop() {
  // Main program code goes here
}`;
    }

    // Add necessary includes for Nano 33 BLE Sense
    let formattedCode = `// Arduino Sketch for Nano 33 BLE Sense Rev2
// Generated by Arduino Blockly Studio

#include <Arduino_LSM9DS1.h>  // IMU library
#include <Arduino_HTS221.h>   // Humidity and Temperature
#include <Arduino_LPS22HB.h>  // Pressure sensor
#include <PDM.h>              // Microphone library

// Global variables for sensor readings
float x, y, z;

`;

    // Add the generated code
    formattedCode += rawCode;

    return formattedCode;
  };

  return (
    <Card className="h-full bg-slate-900/50 border-slate-700 flex flex-col">
      <CardHeader className="flex-shrink-0 pb-3">
        <CardTitle className="flex items-center justify-between text-sm">
          <div className="flex items-center space-x-2">
            <FileCode className="w-4 h-4 text-purple-400" />
            <span className="text-white">Generated Arduino Code</span>
          </div>
          <Button
            onClick={handleCopyCode}
            variant="outline"
            size="sm"
            className="bg-purple-500/20 border-purple-500/30 text-purple-300 hover:bg-purple-500/30"
          >
            <Copy className="w-3 h-3 mr-1" />
            Copy
          </Button>
        </CardTitle>
      </CardHeader>
      
      <CardContent className="flex-1 overflow-hidden p-0">
        <div className="h-full overflow-y-auto">
          <pre className="text-xs text-gray-300 p-4 font-mono whitespace-pre-wrap leading-relaxed">
            <code>{formatArduinoCode(code)}</code>
          </pre>
        </div>
      </CardContent>
      
      <div className="flex-shrink-0 p-3 bg-slate-800/30 border-t border-slate-700">
        <div className="flex items-center justify-between text-xs text-gray-400">
          <span>Lines: {formatArduinoCode(code).split('\n').length}</span>
          <span>Ready for upload</span>
        </div>
      </div>
    </Card>
  );
};
